# Generated by Django 5.1.3 on 2024-11-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_category_game_difficulty_game_type_game_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='type',
        ),
        migrations.AddField(
            model_name='game',
            name='difficulty_multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='questions',
            field=models.JSONField(default=list),
        ),
    ]
